---
version: '3.4'

services:
  ip_service:
    image: docker.sunet.se/ip_service:latest
    networks:
      ip_service_net:
        ipv4_address: 172.16.20.250
    ports:
      - 8080:8080
    volumes:
      - ./dev-config-docker.yaml:/tmp/config.yaml:ro
      - ./templates/:/templates:ro
      - ./assets/:/assets:ro
      - ip_servicedata:/db
    environment:
      - CONFIG_YAML=/tmp/config.yaml

volumes:
  ip_servicedata:
    name: ip_servicedat

networks:
  ip_service_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ips
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24
