basePath: /
definitions:
  apiv1.CollisionReply:
    properties:
      collision:
        type: boolean
    type: object
  apiv1.CollisionRequest:
    properties:
      ip_1:
        type: string
      ip_2:
        type: string
    required:
    - ip_1
    - ip_2
    type: object
  helpers.Error:
    properties:
      details: {}
      title:
        type: string
    type: object
  helpers.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/helpers.Error'
    type: object
  model.BuildVariables:
    properties:
      git_branch:
        type: string
      git_commit:
        type: string
      go_arch:
        type: string
      go_version:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  model.Coordinates:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  model.ReplyIPInformation:
    properties:
      asn:
        type: integer
      asn_organization:
        type: string
      city:
        type: string
      continent:
        type: string
      coordinates:
        $ref: '#/definitions/model.Coordinates'
      country:
        type: string
      country_iso:
        type: string
      hostname:
        type: string
      ip:
        type: string
      ip_decimal:
        type: string
      is_1918_network:
        type: boolean
      is_eu:
        type: boolean
      postal_code:
        type: string
      region:
        type: string
      region_code:
        type: string
      timezone:
        type: string
      user_agent:
        $ref: '#/definitions/useragent.UserAgent'
    type: object
  model.ReplyLookUp:
    properties:
      asn:
        type: integer
      asn_organization:
        type: string
      city:
        type: string
      continent:
        type: string
      coordinates:
        $ref: '#/definitions/model.Coordinates'
      country:
        type: string
      country_iso:
        type: string
      hostname:
        type: string
      ip:
        type: string
      ip_decimal:
        type: string
      is_1918_network:
        type: boolean
      is_eu:
        type: boolean
      postal_code:
        type: string
      ptr:
        items:
          type: string
        type: array
      region:
        type: string
      region_code:
        type: string
      timezone:
        type: string
      whois:
        additionalProperties:
          $ref: '#/definitions/rpsl.Object'
        type: object
    type: object
  model.StatusProbe:
    properties:
      healthy:
        type: boolean
      message:
        additionalProperties: {}
        type: object
      name:
        type: string
      timestamp:
        type: string
    type: object
  model.StatusReply:
    properties:
      data:
        $ref: '#/definitions/model.StatusReplyData'
    type: object
  model.StatusReplyData:
    properties:
      build_variables:
        $ref: '#/definitions/model.BuildVariables'
      probes:
        items:
          $ref: '#/definitions/model.StatusProbe'
        type: array
      service_name:
        type: string
      status:
        type: string
    type: object
  rpsl.ASN:
    additionalProperties:
      $ref: '#/definitions/rpsl.Object'
    type: object
  rpsl.Object:
    properties:
      country:
        items:
          type: string
        type: array
      created:
        items:
          type: string
        type: array
      last-modified:
        type: string
      network:
        type: string
      org:
        type: string
      org-name:
        type: string
      origin:
        type: string
      owner:
        type: string
      ownerid:
        type: string
      remarks:
        items:
          type: string
        type: array
    type: object
  useragent.UserAgent:
    properties:
      bot:
        type: boolean
      desktop:
        type: boolean
      device:
        type: string
      mobile:
        type: boolean
      name:
        type: string
      os:
        type: string
      osversion:
        type: string
      osversionNo:
        $ref: '#/definitions/useragent.VersionNo'
      string:
        type: string
      tablet:
        type: boolean
      url:
        type: string
      version:
        type: string
      versionNo:
        $ref: '#/definitions/useragent.VersionNo'
    type: object
  useragent.VersionNo:
    properties:
      major:
        type: integer
      minor:
        type: integer
      patch:
        type: integer
    type: object
info:
  contact: {}
  title: ip_service API
  version: 0.1.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: ip for the request
      operationId: ip
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.ReplyIPInformation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get IP for the request
      tags:
      - ip_service
  /asn:
    get:
      consumes:
      - application/json
      description: ASN for the given IP
      operationId: asn
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get ASN for the given IP
      tags:
      - ip_service
  /city:
    get:
      consumes:
      - application/json
      description: city for the given IP
      operationId: city
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get city for the given IP
      tags:
      - ip_service
  /collision:
    post:
      consumes:
      - application/json
      description: takes two CIDR blocks and checks if they overlap
      operationId: collision
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/apiv1.CollisionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/apiv1.CollisionReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Check if two CIDR blocks overlap
      tags:
      - ip_service
  /coordinates:
    get:
      consumes:
      - application/json
      description: coordinates for the given IP
      operationId: coordinates
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get Coordinates for the given IP
      tags:
      - ip_service
  /country:
    get:
      consumes:
      - application/json
      description: country for the given IP
      operationId: country
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get country for the given IP
      tags:
      - ip_service
  /country-iso:
    get:
      consumes:
      - application/json
      description: country ISO for the given IP
      operationId: countryISO
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: get Country ISO for the given IP
      tags:
      - ip_service
  /health:
    get:
      consumes:
      - application/json
      description: returns the status of the service
      operationId: status
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.StatusReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Status of the service
      tags:
      - ip_service
  /lookup/{ip}:
    get:
      consumes:
      - application/json
      description: takes query parameter ip and returns all information
      operationId: lookUpIP
      parameters:
      - description: ip
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.ReplyLookUp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Look up all information for the given IP
      tags:
      - ip_service
  /whois/{ip}:
    get:
      consumes:
      - application/json
      description: takes query parameter ip and returns whois information in JSON
        format
      operationId: whois
      parameters:
      - description: ip
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/rpsl.ASN'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Whois information in JSON format
      tags:
      - ip_service
swagger: "2.0"
